package com.dhaval.echo.data.backup

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import androidx.core.content.edit
import dagger.hilt.android.qualifiers.ApplicationContext
import java.nio.ByteBuffer
import java.nio.CharBuffer
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Holds the backup password so unattended backups can encrypt without asking.
 *
 * There is an unavoidable tension here: encryption-by-default and automatic
 * backups together mean the app must be able to seal an archive at 2 a.m. with
 * nobody present. Something has to hold the password. The honest best available
 * on Android is to wrap it with a key that lives in the AndroidKeyStore and
 * cannot be extracted from the device — so the stored blob is useless if the
 * file is copied off the phone, even though it is by construction usable *on*
 * the phone.
 *
 * Two deliberate non-choices:
 *
 *  - **No `setUserAuthenticationRequired`.** It would be stronger, and it would
 *    also break every scheduled backup, since those run precisely when the phone
 *    is locked and idle on a charger.
 *  - **No `setUnlockedDeviceRequired`.** Same reason: overnight is exactly when
 *    backups should run, and overnight the screen is locked.
 *
 * A user who wants a password that exists only in their head can turn off
 * automatic backups and encrypt manual ones by typing it each time; that path
 * is supported and this store simply stays empty.
 */
@Singleton
class BackupPasswordStore @Inject constructor(
    @ApplicationContext context: Context
) {
    private val prefs = context.getSharedPreferences(FILE_NAME, Context.MODE_PRIVATE)

    val hasPassword: Boolean get() = prefs.contains(KEY_BLOB)

    /**
     * @param password zeroed by the caller; this method does not take ownership.
     */
    fun save(password: CharArray) {
        val plain = password.toUtf8Bytes()
        try {
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(Cipher.ENCRYPT_MODE, loadOrCreateKey())
            }
            val sealed = cipher.doFinal(plain)
            // iv || ciphertext. The IV is generated by the cipher rather than by
            // us, so it is never reused across two saves under the same key.
            val blob = ByteArray(cipher.iv.size + sealed.size).also {
                cipher.iv.copyInto(it, 0)
                sealed.copyInto(it, cipher.iv.size)
            }
            prefs.edit {
                putString(KEY_BLOB, Base64.encodeToString(blob, Base64.NO_WRAP))
                putInt(KEY_IV_LENGTH, cipher.iv.size)
            }
        } finally {
            plain.fill(0)
        }
    }

    /**
     * @return the password, or null when none is stored or the key is gone —
     *   which happens legitimately after a factory reset or a restore of app
     *   data onto a different device, since AndroidKeyStore material never
     *   travels. The caller treats that as "no password available" and asks.
     */
    fun read(): CharArray? {
        val encoded = prefs.getString(KEY_BLOB, null) ?: return null
        val ivLength = prefs.getInt(KEY_IV_LENGTH, GCM_IV_BYTES)
        return runCatching {
            val blob = Base64.decode(encoded, Base64.NO_WRAP)
            val cipher = Cipher.getInstance(TRANSFORMATION).apply {
                init(
                    Cipher.DECRYPT_MODE,
                    loadOrCreateKey(),
                    GCMParameterSpec(GCM_TAG_BITS, blob, 0, ivLength)
                )
            }
            val plain = cipher.doFinal(blob, ivLength, blob.size - ivLength)
            try {
                plain.toCharArray()
            } finally {
                plain.fill(0)
            }
        }.getOrNull()
    }

    fun clear() = prefs.edit { remove(KEY_BLOB); remove(KEY_IV_LENGTH) }

    private fun loadOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply { load(null) }
        (keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry)?.let { return it.secretKey }

        return KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE).apply {
            init(
                KeyGenParameterSpec.Builder(
                    KEY_ALIAS,
                    KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
                )
                    .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                    .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                    .setKeySize(256)
                    .build()
            )
        }.generateKey()
    }

    private companion object {
        /** Excluded from Android cloud backup; see res/xml/backup_rules.xml. */
        const val FILE_NAME = "echo_backup_secret"
        const val ANDROID_KEYSTORE = "AndroidKeyStore"
        const val KEY_ALIAS = "echo_backup_password_key"
        const val TRANSFORMATION = "AES/GCM/NoPadding"
        const val GCM_TAG_BITS = 128
        const val GCM_IV_BYTES = 12
        const val KEY_BLOB = "wrapped_password"
        const val KEY_IV_LENGTH = "iv_length"
    }
}

/**
 * Encodes without going through String, so the password never enters the string
 * pool to sit there until some future GC decides otherwise.
 */
private fun CharArray.toUtf8Bytes(): ByteArray {
    val buffer: ByteBuffer = Charsets.UTF_8.encode(CharBuffer.wrap(this))
    return ByteArray(buffer.remaining()).also { buffer.get(it) }
}

private fun ByteArray.toCharArray(): CharArray {
    val buffer: CharBuffer = Charsets.UTF_8.decode(ByteBuffer.wrap(this))
    return CharArray(buffer.remaining()).also { buffer.get(it) }
}
